<?php
/**
 * Database Backup Tasks
 *
 * Dumps the WordPress database tables to a SQL backup file.
 *
 * @package WPCleanAdmin
 * @version 1.8.18
 * @author Tanox
 * @author URI: https://github.com/Tanox
 * @since 1.7.15
 */
namespace WPCleanAdmin;

if ( ! defined( 'ABSPATH' ) ) {
    exit;
}

/**
 * Backup tasks for the Database class.
 */
trait DatabaseBackupTasks {

    /**
     * Backup database
     *
     * @param array $options Backup options
     * @return array Backup results
     */
    public function backup_database( $options = array() ) {
        global $wpdb;

        $results = array(
            'success' => false,
            'message' => \__( 'Database backup failed', WPCA_TEXT_DOMAIN )
        );

        // Set default options
        $default_options = array(
            'tables' => 'all',
            'format' => 'sql',
            'compress' => true
        );

        $options = ( function_exists( '\wp_parse_args' ) ? \wp_parse_args( $options, $default_options ) : array_merge( $default_options, $options ) );

        // Create backup directory if it doesn't exist
        $backup_dir = WPCA_PLUGIN_DIR . 'backups/';
        if ( ! file_exists( $backup_dir ) ) {
            if ( function_exists( 'wp_mkdir_p' ) ) {
                \wp_mkdir_p( $backup_dir );
            } else {
                // Fallback to mkdir with recursive flag
                mkdir( $backup_dir, 0755, true );
            }
        }

        // Generate backup file name
        $backup_file = $backup_dir . 'wpca-backup-' . date( 'Y-m-d-H-i-s' ) . '.' . $options['format'];

        // Get tables to backup
        if ( $options['tables'] === 'all' ) {
            $tables = $wpdb->get_results( $wpdb->prepare( "SHOW TABLES LIKE %s", $wpdb->prefix . '%' ), ARRAY_N );
            $tables = array_column( $tables, 0 );
        } else {
            // Get all valid WordPress tables
            $all_wp_tables = $wpdb->get_results( $wpdb->prepare( "SHOW TABLES LIKE %s", $wpdb->prefix . '%' ), ARRAY_N );
            $all_wp_tables = array_column( $all_wp_tables, 0 );

            // Filter requested tables to only include valid WordPress tables
            $requested_tables = explode( ',', $options['tables'] );
            $tables = array();

            foreach ( $requested_tables as $table ) {
                $table = trim( $table );
                // Only include valid WordPress tables to prevent SQL injection
                if ( in_array( $table, $all_wp_tables ) ) {
                    $tables[] = $table;
                }
            }
        }

        // Start backup
        $backup_content = "-- WordPress Database Backup\n";
        $backup_content .= "-- Generated by WP Clean Admin on " . date( 'Y-m-d H:i:s' ) . "\n";
        $backup_content .= "-- Database: {$wpdb->dbname}\n\n";

        // Backup each table
        foreach ( $tables as $table ) {
            // Table names are SQL identifiers and cannot be passed through $wpdb->prepare()
            // (it would wrap them in quotes, breaking the query). Validate against a safe
            // pattern and wrap with backticks instead.
            if ( ! preg_match( '/^[A-Za-z0-9_]+$/', $table ) ) {
                continue;
            }

            // Get table structure
            $create_table = $wpdb->get_var( "SHOW CREATE TABLE `{$table}`" );
            $backup_content .= "-- Table structure for table `{$table}`\n";
            $backup_content .= "{$create_table};\n\n";

            // Get table data
            $rows = $wpdb->get_results( "SELECT * FROM `{$table}`", ARRAY_A );

            if ( count( $rows ) > 0 ) {
                $backup_content .= "-- Dumping data for table `{$table}`\n";
                $backup_content .= "INSERT INTO `{$table}` VALUES\n";

                $values = array();
                foreach ( $rows as $row ) {
                    $row_values = array();
                    foreach ( $row as $value ) {
                        $row_values[] = $wpdb->prepare( '%s', $value );
                    }
                    $values[] = "(" . implode( ',', $row_values ) . ")";
                }

                $backup_content .= implode( ",\n", $values ) . ";\n\n";
            }
        }

        // Save backup file
        if ( file_put_contents( $backup_file, $backup_content ) !== false ) {
            $results['success'] = true;
            $results['message'] = \__( 'Database backup created successfully', WPCA_TEXT_DOMAIN );
            $results['file'] = basename( $backup_file );
            $results['size'] = filesize( $backup_file );
        }

        return $results;
    }
}
